let form = document.querySelector("form");
let inputs = document.querySelectorAll("input");
form.addEventListener("submit",(data)=>{
data.preventDefault();
let main = document.createElement("div");
main.classList.add("main");
let card_container = document.createElement("div");
card_container.classList.add("card-container");
let profile_pic = document.createElement("div");
profile_pic.classList.add("profile-pic");
let img = document.createElement("img");
let name = document.createElement("h1");
name.classList.add("name");
let occupation = document.createElement("h3");
occupation.classList.add("occupation");
let info = document.createElement("p");
info.classList.add("info");
img.setAttribute("src", inputs[0].value);
name.textContent = inputs[1].value;
occupation.textContent = inputs[2].value;
info.textContent = inputs[3].value;
profile_pic.appendChild(img);
card_container.appendChild(profile_pic);
card_container.appendChild(name);
card_container.appendChild(occupation);
card_container.appendChild(info);
main.appendChild(card_container);
document.body.appendChild(main);
form.classList.add("form");
let new_card = document.createElement("button");
new_card.classList.add("new-card");
new_card.type = "button";
new_card.textContent = "Create New Card";
card_container.appendChild(new_card);
new_card.addEventListener("click",()=>{
    window.location.reload();
});
});